service: serverless-wedding-rsvp-notifications

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  role: ${file(../serverless-wedding-infrastructure/config.${self:provider.stage}.json):rsvp_handler_role_arn.value}

plugins:
  - serverless-python-requirements

custom:
  vars: ${file(../serverless-wedding-infrastructure/config.${self:provider.stage}.json)}
  pythonRequirements:
    dockerizePip: non-linux

functions:
  rsvp-notification:
    handler: handler.send_rsvp_notification
    events:
      - stream:
          type: dynamodb
          arn:  ${self:custom.vars.rsvp_table_stream_arn.value}
          batchSize: 10
          startingPosition: LATEST

        
